[tool.poetry]
name = "ibkr_trade_log"
version = "0.0.0-dev"
description = ""
authors = ["Jiamin Zhu <github@jiamin.io>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.5"
ib-insync = "^0.9.70"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
